/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#pragma once

#include <format>
#include <fstream>
#include <optional>
#include <string>
#include <utility>

#include "common.h"       // qboolean, link_t, STRUCT_FROM_LINK
#include "entity_state.h" // entity_state_t

#include "pr_comp.h"  // defs shared with qcc
#include "progdefs.h" // generated by program cdefs

typedef union eval_s {
    string_t string;
    float _float;
    float vector[3];
    func_t function;
    int _int;
    int edict;
} eval_t;

#define MAX_ENT_LEAFS 16
struct edict_t
{
    qboolean free;
    link_t area; // linked to a division node or leaf

    int num_leafs;
    short leafnums[MAX_ENT_LEAFS];

    entity_state_t baseline;

    float freetime; // sv.time when the object was freed
    entvars_t v;    // C exported fields from progs
    // other fields from progs come immediately after
};
#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l, edict_t, area)

//============================================================================

extern dprograms_t *progs;
extern dfunction_t *pr_functions;
extern char *pr_strings;
extern ddef_t *pr_globaldefs;
extern ddef_t *pr_fielddefs;
extern dstatement_t *pr_statements;
extern globalvars_t *pr_global_struct;
extern float *pr_globals;    // same as pr_global_struct
extern char *pr_string_temp; // temp string buffer, hunk-allocated so offset from pr_strings fits in int

extern int pr_edict_size; // in bytes

//============================================================================

void PR_Init(void);

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs(void);
void PR_ValidateOperandTypes(void); // called by PR_LoadProgs; exposed so tests can drive it against synthetic data

void PR_Profile_f(void);

edict_t *ED_Alloc(void);
void ED_Free(edict_t *ed);
void ED_ClearEdict(edict_t *e); // zeroes e->v and clears e->free -- the correct way to reset an edict's fields

// Narrow accessors onto pr_global_struct/progs -- the mirror image of
// server.h's SV_* accessors: those let the VM touch app state without
// reaching into sv./svs. by name, these let the APP (host.cpp/host_cmd.cpp/
// sv_main.cpp/sv_move.cpp/sv_phys.cpp/world.cpp) touch VM state without
// reaching into pr_global_struct/progs by name. See
// project_quake_vm_separation.md, phase 7.

// The dominant calling convention throughout sv_phys.cpp/world.cpp/
// host.cpp/host_cmd.cpp/sv_main.cpp: set self (and usually other, reset to
// the world entity when there is no real "other"), then invoke a QC
// function. Collapsing the 2-3 raw pr_global_struct-> assignments these
// call sites used to do by hand into one call removes the chance of
// forgetting one of them.
void PR_ExecuteEntityFunction(edict_t *self, func_t fnum);               // other reset to the world entity
void PR_ExecuteEntityFunction(edict_t *self, edict_t *other, func_t fnum);

// Self/time primitives, for the handful of call sites that don't fit the
// shape above: host.cpp's explicit save/restore around ClientDisconnect,
// sv_move.cpp's read of the currently-executing function's self, and the
// entry points that only need one of self/time set (or already have self
// set from a preceding call).
edict_t *PR_GetSelf(void);
void PR_SetSelf(edict_t *self);
edict_t *PR_GetOther(void);
void PR_SetOther(edict_t *other);
void PR_SetGlobalTime(double time);
void PR_SetFrameTime(float frametime);

// Game-mode/level config -- set once at level spawn (SV_SpawnServer),
// read from various places afterward (host_cmd.cpp's cheat-command guards,
// item-flags encoding).
qboolean PR_IsDeathmatch(void);
void PR_SetGameMode(qboolean isDeathmatch, qboolean isCoop);
void PR_SetMapName(const char *name);
int PR_GetServerFlags(void);
void PR_SetServerFlags(int flags);

// Spawn parms (parm1..parm16, NUM_SPAWN_PARMS of them) -- carries a
// client's inventory/stats across a changelevel. Replaces raw
// (&pr_global_struct->parm1)[i] pointer arithmetic, which silently
// depended on progdefs.q1 laying those 16 floats out contiguously.
float PR_GetSpawnParm(int index); // 0-based, 0..NUM_SPAWN_PARMS-1
void PR_SetSpawnParm(int index, float value);

// Intermission stats, read-only from the app side -- QC increments these
// itself; the engine only ever reports them (host_cmd.cpp's svc_updatestat
// messages).
int PR_TotalSecrets(void);
int PR_TotalMonsters(void);
int PR_FoundSecrets(void);
int PR_KilledMonsters(void);

// sv_phys.cpp's per-frame "did anything ask for a forced relink" flag:
// checked once per entity, decremented once per frame if set.
qboolean PR_ForceRetouchPending(void);
void PR_DecrementForceRetouch(void);

char *ED_NewString(const char *string);
// returns a copy of the string allocated from the server's string heap

void ED_Print(edict_t *ed);
void ED_Write(std::ofstream &f, edict_t *ed);
std::optional<ddef_t *> ED_FindField(const char *name);
std::optional<dfunction_t *> ED_FindFunction(const char *name);
const char *ED_ParseEdict(const char *data, edict_t *ent);

void ED_WriteGlobals(std::ofstream &f);
void ED_ParseGlobals(const char *data);

void ED_LoadFromFile(const char *data);

// define EDICT_NUM(n) ((edict_t *)(sv.edicts+ (n)*pr_edict_size))
// define NUM_FOR_EDICT(e) ((reinterpret_cast<byte*>(e) - sv.edicts)/pr_edict_size)

edict_t *EDICT_NUM(int n);
int NUM_FOR_EDICT(edict_t *e);
edict_t *PROG_TO_EDICT(int prog);
int EDICT_TO_PROG(edict_t *e);
edict_t *NEXT_EDICT(edict_t *e);

//============================================================================

#define G_FLOAT(o) (pr_globals[o])
#define G_INT(o) (*reinterpret_cast<int *>(&pr_globals[o]))
edict_t *G_EDICT(int ofs);
int G_EDICTNUM(int ofs);
#define G_VECTOR(o) (&pr_globals[o])
#define G_STRING(o) (PR_GetString(*reinterpret_cast<string_t *>(&pr_globals[o])))
#define G_FUNCTION(o) (*reinterpret_cast<func_t *>(&pr_globals[o]))

#define E_FLOAT(e, o) ((reinterpret_cast<float *>(&e->v))[o])
#define E_INT(e, o) (*reinterpret_cast<int *>(&(reinterpret_cast<float *>(&e->v))[o]))
#define E_VECTOR(e, o) (&(reinterpret_cast<float *>(&e->v))[o])
#define E_STRING(e, o) (PR_GetString(*reinterpret_cast<string_t *>(&(reinterpret_cast<float *>(&e->v))[o])))

// string_t indirection (pr_edict.cpp): resolves any string_t -- a static
// pr_strings offset, or a dynamic handle from PR_SetString -- to its text.
// See the definitions for the encoding (negative = dynamic) and why
// pr_string_temp's ftos()/vtos() results don't need to change at all.
char *PR_GetString(string_t num);
string_t PR_SetString(const char *s);

extern int type_size[8];

typedef void (*builtin_t)(void);
extern builtin_t *pr_builtins;
extern int pr_numbuiltins;

// PR_ExecuteProgram's per-call-stack-frame interpreter state: the call
// stack, the locals-save stack, and the currently-executing statement/
// function. Still a single file-scope instance (pr_vm, in pr_exec.cpp) --
// only one VM possible by construction, same as every other global-state
// singleton in this codebase (con/sound/mem/net/cl/sv) -- but now named
// and grouped instead of being bare, ungrouped globals.
struct pr_vm_state_t
{
    struct prstack_t
    {
        int s;
        dfunction_t *f;
    };

    static constexpr int MAX_STACK_DEPTH = 32;
    static constexpr int LOCALSTACK_SIZE = 2048;

    prstack_t stack[MAX_STACK_DEPTH]{};
    int depth = 0;

    int localstack[LOCALSTACK_SIZE]{};
    int localstack_used = 0;

    qboolean trace = false;
    dfunction_t *xfunction = nullptr;
    int xstatement = 0;

    int argc = 0; // number of arguments passed to the builtin currently executing
};
extern pr_vm_state_t pr_vm;

extern unsigned short pr_crc;

// Aborts with an already-formatted error message; defined in pr_exec.cpp.
[[noreturn]] void PR_RunErrorImpl(const std::string &error);

template <typename... Args> [[noreturn]] void PR_RunError(std::format_string<Args...> error, Args &&...args)
{
    PR_RunErrorImpl(std::format(error, std::forward<Args>(args)...));
}

void ED_PrintEdicts(void);
void ED_PrintNum(int ent);

std::optional<eval_t *> GetEdictFieldValue(edict_t *ed, const char *field);
