/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#pragma once

#include <format>
#include <fstream>
#include <optional>
#include <string>
#include <utility>

#include "common.h"       // qboolean, link_t, STRUCT_FROM_LINK
#include "entity_state.h" // entity_state_t

#include "pr_comp.h"  // defs shared with qcc
#include "progdefs.h" // generated by program cdefs

typedef union eval_s {
    string_t string;
    float _float;
    float vector[3];
    func_t function;
    int _int;
    int edict;
} eval_t;

#define MAX_ENT_LEAFS 16
struct edict_t
{
    qboolean free;
    link_t area; // linked to a division node or leaf

    int num_leafs;
    short leafnums[MAX_ENT_LEAFS];

    entity_state_t baseline;

    float freetime; // sv.time when the object was freed
    entvars_t v;    // C exported fields from progs
    // other fields from progs come immediately after
};
#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l, edict_t, area)

//============================================================================

extern dprograms_t *progs;
extern dfunction_t *pr_functions;
extern char *pr_strings;
extern ddef_t *pr_globaldefs;
extern ddef_t *pr_fielddefs;
extern dstatement_t *pr_statements;
extern globalvars_t *pr_global_struct;
extern float *pr_globals;    // same as pr_global_struct
extern char *pr_string_temp; // temp string buffer, hunk-allocated so offset from pr_strings fits in int

extern int pr_edict_size; // in bytes

//============================================================================

void PR_Init(void);

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs(void);

void PR_Profile_f(void);

edict_t *ED_Alloc(void);
void ED_Free(edict_t *ed);

char *ED_NewString(const char *string);
// returns a copy of the string allocated from the server's string heap

void ED_Print(edict_t *ed);
void ED_Write(std::ofstream &f, edict_t *ed);
std::optional<ddef_t *> ED_FindField(const char *name);
std::optional<dfunction_t *> ED_FindFunction(const char *name);
const char *ED_ParseEdict(const char *data, edict_t *ent);

void ED_WriteGlobals(std::ofstream &f);
void ED_ParseGlobals(const char *data);

void ED_LoadFromFile(const char *data);

// define EDICT_NUM(n) ((edict_t *)(sv.edicts+ (n)*pr_edict_size))
// define NUM_FOR_EDICT(e) ((reinterpret_cast<byte*>(e) - sv.edicts)/pr_edict_size)

edict_t *EDICT_NUM(int n);
int NUM_FOR_EDICT(edict_t *e);
edict_t *PROG_TO_EDICT(int prog);
int EDICT_TO_PROG(edict_t *e);
edict_t *NEXT_EDICT(edict_t *e);

//============================================================================

#define G_FLOAT(o) (pr_globals[o])
#define G_INT(o) (*reinterpret_cast<int *>(&pr_globals[o]))
edict_t *G_EDICT(int ofs);
int G_EDICTNUM(int ofs);
#define G_VECTOR(o) (&pr_globals[o])
#define G_STRING(o) (pr_strings + *reinterpret_cast<string_t *>(&pr_globals[o]))
#define G_FUNCTION(o) (*reinterpret_cast<func_t *>(&pr_globals[o]))

#define E_FLOAT(e, o) ((reinterpret_cast<float *>(&e->v))[o])
#define E_INT(e, o) (*reinterpret_cast<int *>(&(reinterpret_cast<float *>(&e->v))[o]))
#define E_VECTOR(e, o) (&(reinterpret_cast<float *>(&e->v))[o])
#define E_STRING(e, o) (pr_strings + *reinterpret_cast<string_t *>(&(reinterpret_cast<float *>(&e->v))[o]))

extern int type_size[8];

typedef void (*builtin_t)(void);
extern builtin_t *pr_builtins;
extern int pr_numbuiltins;

// PR_ExecuteProgram's per-call-stack-frame interpreter state: the call
// stack, the locals-save stack, and the currently-executing statement/
// function. Still a single file-scope instance (pr_vm, in pr_exec.cpp) --
// only one VM possible by construction, same as every other global-state
// singleton in this codebase (con/sound/mem/net/cl/sv) -- but now named
// and grouped instead of being bare, ungrouped globals.
struct pr_vm_state_t
{
    struct prstack_t
    {
        int s;
        dfunction_t *f;
    };

    static constexpr int MAX_STACK_DEPTH = 32;
    static constexpr int LOCALSTACK_SIZE = 2048;

    prstack_t stack[MAX_STACK_DEPTH]{};
    int depth = 0;

    int localstack[LOCALSTACK_SIZE]{};
    int localstack_used = 0;

    qboolean trace = false;
    dfunction_t *xfunction = nullptr;
    int xstatement = 0;

    int argc = 0; // number of arguments passed to the builtin currently executing
};
extern pr_vm_state_t pr_vm;

extern unsigned short pr_crc;

// Aborts with an already-formatted error message; defined in pr_exec.cpp.
[[noreturn]] void PR_RunErrorImpl(const std::string &error);

template <typename... Args> [[noreturn]] void PR_RunError(std::format_string<Args...> error, Args &&...args)
{
    PR_RunErrorImpl(std::format(error, std::forward<Args>(args)...));
}

void ED_PrintEdicts(void);
void ED_PrintNum(int ent);

std::optional<eval_t *> GetEdictFieldValue(edict_t *ed, const char *field);
