/*
Copyright (C) 1996-1997 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

#pragma once

#include <format>
#include <fstream>
#include <optional>
#include <string>
#include <utility>

#include "common.h"       // qboolean, link_t, STRUCT_FROM_LINK
#include "entity_state.h" // entity_state_t

#include "pr_comp.h"  // defs shared with qcc
#include "progdefs.h" // generated by program cdefs

typedef union eval_s {
    string_t string;
    float _float;
    float vector[3];
    func_t function;
    int _int;
    int edict;
} eval_t;

#define MAX_ENT_LEAFS 16
struct edict_t
{
    qboolean free;
    link_t area; // linked to a division node or leaf

    int num_leafs;
    short leafnums[MAX_ENT_LEAFS];

    entity_state_t baseline;

    float freetime; // sv.time when the object was freed
    entvars_t v;    // C exported fields from progs
    // other fields from progs come immediately after
};
#define EDICT_FROM_AREA(l) STRUCT_FROM_LINK(l, edict_t, area)

//============================================================================

extern dprograms_t *progs;
extern dfunction_t *pr_functions;
extern char *pr_strings;
extern ddef_t *pr_globaldefs;
extern ddef_t *pr_fielddefs;
extern dstatement_t *pr_statements;
extern globalvars_t *pr_global_struct;
extern float *pr_globals;    // same as pr_global_struct
extern char *pr_string_temp; // temp string buffer, hunk-allocated so offset from pr_strings fits in int

// pr_edict_size moved to server.h -- see EDICT_NUM's note above.

//============================================================================

void PR_ExecuteProgram(func_t fnum);
void PR_LoadProgs(void);
void PR_ValidateOperandTypes(void); // called by PR_LoadProgs; exposed so tests can drive it against synthetic data

void PR_Profile_f(void);

edict_t *ED_Alloc(void);
void ED_Free(edict_t *ed);

// Everything that used to be declared here for app code (host.cpp/
// host_cmd.cpp/sv_main.cpp/sv_move.cpp/sv_phys.cpp/world.cpp) -- self/
// other/time, game-mode/level config, spawn parms, intermission stats,
// force-retouch, ED_ClearEdict, string resolution, savegame read/write --
// is now reached through qc_backend.h's g_qcBackend instead of a bare
// PR_-prefixed free function. That's the actual swappable app-facing
// interface; this header (progs.h) is the QuakeC backend's own internals.
// See project_quake_vm_separation.md, phase 8.

char *ED_NewString(const char *string);
// returns a copy of the string allocated from the server's string heap

void ED_Print(edict_t *ed);
void ED_Write(std::ofstream &f, edict_t *ed);
std::optional<ddef_t *> ED_FindField(const char *name);
std::optional<dfunction_t *> ED_FindFunction(const char *name);
const char *ED_ParseEdict(const char *data, edict_t *ent);

void ED_WriteGlobals(std::ofstream &f);
void ED_ParseGlobals(const char *data);

// ED_LoadFromFile is now only called via qc_backend_t::SpawnEntitiesForLevel
// (qc_backend.h) -- no declaration needed here, only pr_edict.cpp calls it.

// EDICT_NUM/NUM_FOR_EDICT/PROG_TO_EDICT/EDICT_TO_PROG/NEXT_EDICT/
// pr_edict_size moved to server.h -- they're pure array-index/pointer/
// prog-offset conversions over sv.edicts (app-owned), not QC-interpreter
// logic. See qc_backend.h, phase 8.

//============================================================================

#define G_FLOAT(o) (pr_globals[o])
#define G_INT(o) (*reinterpret_cast<int *>(&pr_globals[o]))
edict_t *G_EDICT(int ofs);
int G_EDICTNUM(int ofs);
#define G_VECTOR(o) (&pr_globals[o])
#define G_STRING(o) (PR_GetString(*reinterpret_cast<string_t *>(&pr_globals[o])))
#define G_FUNCTION(o) (*reinterpret_cast<func_t *>(&pr_globals[o]))

#define E_FLOAT(e, o) ((reinterpret_cast<float *>(&e->v))[o])
#define E_INT(e, o) (*reinterpret_cast<int *>(&(reinterpret_cast<float *>(&e->v))[o]))
#define E_VECTOR(e, o) (&(reinterpret_cast<float *>(&e->v))[o])
#define E_STRING(e, o) (PR_GetString(*reinterpret_cast<string_t *>(&(reinterpret_cast<float *>(&e->v))[o])))

// string_t indirection (pr_edict.cpp): resolves any string_t -- a static
// pr_strings offset, or a dynamic handle from PR_SetString -- to its text.
// See the definitions for the encoding (negative = dynamic) and why
// pr_string_temp's ftos()/vtos() results don't need to change at all.
char *PR_GetString(string_t num);
string_t PR_SetString(const char *s);

extern int type_size[8];

typedef void (*builtin_t)(void);
extern builtin_t *pr_builtins;
extern int pr_numbuiltins;

// PR_ExecuteProgram's per-call-stack-frame interpreter state: the call
// stack, the locals-save stack, and the currently-executing statement/
// function. Still a single file-scope instance (pr_vm, in pr_exec.cpp) --
// only one VM possible by construction, same as every other global-state
// singleton in this codebase (con/sound/mem/net/cl/sv) -- but now named
// and grouped instead of being bare, ungrouped globals.
struct pr_vm_state_t
{
    struct prstack_t
    {
        int s;
        dfunction_t *f;
    };

    static constexpr int MAX_STACK_DEPTH = 32;
    static constexpr int LOCALSTACK_SIZE = 2048;

    prstack_t stack[MAX_STACK_DEPTH]{};
    int depth = 0;

    int localstack[LOCALSTACK_SIZE]{};
    int localstack_used = 0;

    qboolean trace = false;
    dfunction_t *xfunction = nullptr;
    int xstatement = 0;

    int argc = 0; // number of arguments passed to the builtin currently executing
};
extern pr_vm_state_t pr_vm;

extern unsigned short pr_crc;

// Aborts with an already-formatted error message; defined in pr_exec.cpp.
[[noreturn]] void PR_RunErrorImpl(const std::string &error);

template <typename... Args> [[noreturn]] void PR_RunError(std::format_string<Args...> error, Args &&...args)
{
    PR_RunErrorImpl(std::format(error, std::forward<Args>(args)...));
}

void ED_PrintEdicts(void);
void ED_PrintNum(int ent);

std::optional<eval_t *> GetEdictFieldValue(edict_t *ed, const char *field);
